### ISSUE TITLE
Add docker setup

### ISSUE THREAD

**Issue by shivkatira** [HydPy/pyconfhyd2025#24]
Add Dockerfile and docker-compose.yaml

**Comment by RajatRajdeep** [comment]
Hi @shivkatira,
Thank you for the PR! I believe adding Docker might not be necessary for this project because:
- The app is quite simple, with minimal dependencies, and there are no plans to add additional dependencies.
- There are no plans to modify the current deployment preview setup or github  pages hosting process.

Given this, using Docker could be an overkill for this use case.

**Comment by bhansa** [comment]
Also, I would encourage to use project export assets instead of exposing on a port if we're not using any server side features.

**Comment by shivkatira** [comment]
@RajatRajdeep @bhansa  thanx for the feedback.
